In [1]:

import tensorflow as tf

In [2]:
tf.__version__

'2.2.0'

In [3]:
import numpy as np
import pandas as pd

In [4]:
np.__version__

'1.19.5'

In [5]:
pd.__version__

'1.1.5'

In [6]:
# to check the version of tensorflow and keras

print("Tensorflow version:", tf.__version__)
print("Keras version:", tf.keras.__version__)

Tensorflow version: 2.2.0
Keras version: 2.3.0-tf


In [8]:
# to check if code is run by GPU or CPU

var = tf.Variable([3,3])
if tf.test.is_gpu_available():
  print("GPU")
  print("GPU #0?")
  print(var.device.endswith("GPU:0"))
else:
  print("CPU")

GPU
GPU #0?
False


In [9]:
tf.test.is_gpu_available(cuda_only=False, min_cuda_compute_capability=None)

True

In [10]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [12]:
# Tensorflow basics

In [11]:
x = tf.constant(42)
x

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [12]:
# in TF 1.x we used to call Session() and sess.rn()
# in TF 2.x the thing is handled without those

x.numpy()

42

In [13]:
!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.


In [14]:
x = tf.constant([1,1,2] ,dtype = tf.int64)
x

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 1, 2], dtype=int64)>

In [15]:
x.numpy()

array([1, 1, 2], dtype=int64)

In [16]:
x = tf.constant([[4,2],[9,5]])
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 2],
       [9, 5]])>

In [17]:
x.numpy()

array([[4, 2],
       [9, 5]])

In [18]:
# converting numpy array to tensor and vice-versa

x_ten = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
x_ten

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [19]:
# x_ten is a tensor. to convert to numpy:

x_num = x_ten.numpy()
x_num

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
# x_num is a numpy array. To convert to tensor:

x_tennew = tf.constant(x_num)
x_tennew

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [21]:
print("shape:", x_tennew.shape)
print("Data type:", x_tennew.dtype)

shape: (3, 3)
Data type: <dtype: 'int32'>


In [22]:
# To create an array with zeros and ones:
# similar to np.ones and np.zeros, we have tf.ones and tf.zeros

x = tf.ones([3,4], tf.int64)
x

<tf.Tensor: shape=(3, 4), dtype=int64, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)>

In [23]:
x = tf.ones(shape=(3,4), dtype=tf.int32)
x

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])>

In [24]:
x = tf.ones((3,4))
x

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [25]:
y = tf.zeros([2,2], tf.int32)
y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]])>

In [26]:
y = tf.zeros(shape=(3,4), dtype=tf.int32)
y

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])>

In [27]:
y = tf.zeros((3,4))
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [28]:
# elementwise operations

const1 = tf.constant([[1,2,3],[4,5,6]])
const2 = tf.constant([[4,5,6],[1,2,3]])
result = tf.add(const1,const2)
result

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[5, 7, 9],
       [5, 7, 9]])>

In [29]:
result2 = tf.subtract(const1, const2)
result2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[-3, -3, -3],
       [ 3,  3,  3]])>

In [30]:
result3 = tf.multiply(const1, const2)
result3

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 4, 10, 18],
       [ 4, 10, 18]])>

In [31]:
# Similarly we can persorm more operations by tf.(presstab) and select the various math op.

# the same method can be used for matrix multiplication.

# please keep in mind the shape of the tensor before doing the operation to avoid and error.

In [32]:
# standard normal dist - mean = 0, std_div = 1.0
# normal dist - mean = anything, std_div = anything , {both gives the bell curve}

In [33]:
# to create a random values:

tf.random.normal(shape=(2,2), mean = 0, stddev=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.32962337,  0.61070967],
       [ 1.4472648 ,  0.14491753]], dtype=float32)>

In [34]:
tf.random.uniform(shape=(4,3,2),minval=2, maxval=8, dtype=tf.int32)

# please note above for shape (x,y) x=rows, y=columns
# for shape(h,x,y) h=height, x=rows, y=columns

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[6, 5],
        [5, 7],
        [2, 4]],

       [[3, 6],
        [3, 3],
        [6, 3]],

       [[2, 7],
        [2, 6],
        [5, 4]],

       [[5, 6],
        [5, 5],
        [7, 7]]])>

In [35]:
tf.random.normal(shape = (3,2), mean = 10, stddev=2, dtype=tf.float32, seed=None, name= None)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 9.656605,  9.696197],
       [10.528255, 12.335239],
       [ 9.201324,  8.04521 ]], dtype=float32)>

In [36]:
random_num = tf.random.normal(shape=(3,2), mean=10.0, stddev=2.0)
random_num

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.502698,  7.949621],
       [13.772023,  7.757759],
       [11.381517, 13.858603]], dtype=float32)>

In [37]:
tf.random.uniform(shape = (2,4), minval=0, maxval=None, dtype=tf.float32, seed=None, name= None)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.32154942, 0.00272143, 0.5538926 , 0.96359503],
       [0.73822415, 0.8691149 , 0.64963007, 0.804288  ]], dtype=float32)>

In [38]:
# setting the SEED
# when we set seed value then the random data generated will be same for all users.

tf.random.set_seed(11)

In [40]:
random_num1 = tf.random.uniform(shape=(2,2), maxval=10, dtype=tf.int32)
random_num2 = tf.random.uniform(shape=(2,2), maxval=10, dtype=tf.int32)
print(random_num1)
print(random_num2)

tf.Tensor(
[[6 7]
 [0 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[6 8]
 [0 4]], shape=(2, 2), dtype=int32)


In [41]:
# Adding and concatenation in tensorflow

dice1 = tf.Variable(tf.random.uniform([10,1], minval=1, maxval=7, dtype=tf.int32))
dice2 = tf.Variable(tf.random.uniform([10,1], minval=1, maxval=7, dtype=tf.int32))

# adding the values
dice_sum = dice1 + dice2
dice_sum

<tf.Tensor: shape=(10, 1), dtype=int32, numpy=
array([[10],
       [ 4],
       [ 6],
       [ 5],
       [ 4],
       [10],
       [ 7],
       [ 4],
       [ 7],
       [ 9]])>

In [42]:
final_dice = tf.concat(values=[dice1, dice2, dice_sum], axis=1)
final_dice

<tf.Tensor: shape=(10, 3), dtype=int32, numpy=
array([[ 5,  5, 10],
       [ 2,  2,  4],
       [ 4,  2,  6],
       [ 1,  4,  5],
       [ 3,  1,  4],
       [ 5,  5, 10],
       [ 6,  1,  7],
       [ 1,  3,  4],
       [ 2,  5,  7],
       [ 3,  6,  9]])>

In [43]:
final_dice = tf.concat(values=[dice1, dice2, dice_sum], axis=0)
final_dice

<tf.Tensor: shape=(30, 1), dtype=int32, numpy=
array([[ 5],
       [ 2],
       [ 4],
       [ 1],
       [ 3],
       [ 5],
       [ 6],
       [ 1],
       [ 2],
       [ 3],
       [ 5],
       [ 2],
       [ 2],
       [ 4],
       [ 1],
       [ 5],
       [ 1],
       [ 3],
       [ 5],
       [ 6],
       [10],
       [ 4],
       [ 6],
       [ 5],
       [ 4],
       [10],
       [ 7],
       [ 4],
       [ 7],
       [ 9]])>

In [44]:

# 1-D tensor

tensor_1d = tf.constant([12,11,51,42,6,16,-8,-19,31])  # creating 1-D tensor
tensor_1d          # printing 1_D tensor

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 12,  11,  51,  42,   6,  16,  -8, -19,  31])>

In [45]:
# argmax and argmin
i = tf.argmax(input = tensor_1d)
print(i)
j = tf.argmin(input= tensor_1d)
print(j)

tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)


In [46]:
print("index of max value:", i.numpy())
print("max value in tensor:", tensor_1d[i].numpy())

index of max value: 2
max value in tensor: 51


In [47]:
print("index of min value:", j.numpy())
print("min value in tensor:", tensor_1d[j].numpy())

index of min value: 7
min value in tensor: -19


In [48]:
# tf.constant() when used we cant change the data stored.
# for using on the weight updation in back prop'n we need to change the value of the variable.
# So we use tf.variable() to be able to change the value in the run time.

In [49]:
var0 = 24                            # noramal python variable
var1 = tf.Variable(42)               # rank 0 tensor
var2 = tf.Variable([[[1,2,3],[4,5,6]],[[1,4,7],[2,5,8]]])   # rank 3 tensor
(var0, var1, var2)

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
 array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 4, 7],
         [2, 5, 8]]])>)

In [50]:
# Specifying the datatype

In [51]:
float_var64 = tf.Variable(89, dtype=tf.float64)
float_var64

<tf.Variable 'Variable:0' shape=() dtype=float64, numpy=89.0>

In [52]:
# reassigning a tf.variable

In [53]:
x = tf.Variable(53.0)
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=53.0>

In [54]:
x.assign(59.2)
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=59.2>

In [55]:
x = tf.random.normal(shape=(2,3)) # Creating a 2x3 matrix and assigning a random values.
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.2842556 , -0.4905156 ,  0.7645078 ],
       [ 0.41764784, -1.7386407 , -1.069378  ]], dtype=float32)>

In [56]:
y = tf.Variable(x)         # Then convering the random value matrix to a variable.
y

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[-0.2842556 , -0.4905156 ,  0.7645078 ],
       [ 0.41764784, -1.7386407 , -1.069378  ]], dtype=float32)>

In [57]:
z = tf.random.normal(shape=(2,3))       # creating a new matrix of the same shape.
z

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.6636649 ,  0.84493214,  0.25897932],
       [-0.57181484,  0.2893756 , -0.20143197]], dtype=float32)>

In [58]:
y.assign(z)                  # replacing the value of the z matrix in the y matrix

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 1.6636649 ,  0.84493214,  0.25897932],
       [-0.57181484,  0.2893756 , -0.20143197]], dtype=float32)>

In [60]:
for i in range(2):
    for j in range(2):
        assert y[i,j] == z[i,j] 

In [61]:
y

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 1.6636649 ,  0.84493214,  0.25897932],
       [-0.57181484,  0.2893756 , -0.20143197]], dtype=float32)>

In [62]:
y.assign_add(tf.ones([2,3]))  # adding one to y 
y

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[2.6636648 , 1.8449321 , 1.2589793 ],
       [0.42818516, 1.2893755 , 0.798568  ]], dtype=float32)>

In [63]:
# just for checking and confirming.

for i in range(2):
    for j in range(2):
        assert y[i,j] == z[i,j]

AssertionError: 

In [64]:
for i in range(2):
    for j in range(2):
        assert y[i,j] == z[i,j] + 1

In [65]:
# shaping of the tensor

tensorr = tf.Variable(tf.random.uniform(shape=(2,2,8), minval=0, maxval=10, dtype=tf.int64))
print(tensorr)
print(tensorr.shape)

<tf.Variable 'Variable:0' shape=(2, 2, 8) dtype=int64, numpy=
array([[[0, 8, 5, 1, 2, 8, 4, 8],
        [1, 7, 9, 9, 3, 1, 7, 3]],

       [[2, 2, 3, 1, 6, 8, 0, 4],
        [5, 8, 0, 8, 0, 4, 5, 4]]], dtype=int64)>
(2, 2, 8)


In [66]:
# Reshaping the tensor.
# NOTE we can also reshape the number of clolumns, rows as well as HEIGHT 

ten1 = tf.reshape(tensorr, [2,4,4])
ten2 = tf.reshape(tensorr, [4,1,8])
print(ten1)
print(ten2)

tf.Tensor(
[[[0 8 5 1]
  [2 8 4 8]
  [1 7 9 9]
  [3 1 7 3]]

 [[2 2 3 1]
  [6 8 0 4]
  [5 8 0 8]
  [0 4 5 4]]], shape=(2, 4, 4), dtype=int64)
tf.Tensor(
[[[0 8 5 1 2 8 4 8]]

 [[1 7 9 9 3 1 7 3]]

 [[2 2 3 1 6 8 0 4]]

 [[5 8 0 8 0 4 5 4]]], shape=(4, 1, 8), dtype=int64)


In [67]:
# Rank of the matrix(remember it as a degree of the matrix given)

# the number of indices required to uniquely select each element of the tensor.

tensorr

<tf.Variable 'Variable:0' shape=(2, 2, 8) dtype=int64, numpy=
array([[[0, 8, 5, 1, 2, 8, 4, 8],
        [1, 7, 9, 9, 3, 1, 7, 3]],

       [[2, 2, 3, 1, 6, 8, 0, 4],
        [5, 8, 0, 8, 0, 4, 5, 4]]], dtype=int64)>

In [68]:
tf.rank(tensorr)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [69]:
tensorr[1][1][3].numpy()

# we used 3 indices to uniquely define a number. so the rank is 3.

8

In [70]:
# we can also get the element similar to above process by this code as well

tensorr[1,1,3].numpy()   # tensor to numpy

8

In [71]:
#Finding the size and length of the matrix

In [72]:
tf_size = tf.size(tensorr)
print(tf_size)
tf_size.numpy()

tf.Tensor(32, shape=(), dtype=int32)


32

In [74]:
#Some math operations

a = tf.round(tf.random.uniform(shape=(2,2), minval=1, maxval=5, dtype=tf.float32))

b = tf.round(tf.random.uniform(shape=(2,2), minval=2, maxval=6, dtype=tf.float32))

c = tf.round(a + b)

d = tf.add(a,b)

e = tf.square(c)

f = tf.exp(c)

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

tf.Tensor(
[[3. 4.]
 [1. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[4. 5.]
 [4. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[7. 9.]
 [5. 8.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[7. 9.]
 [5. 8.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[49. 81.]
 [25. 64.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1096.6332  8103.084  ]
 [ 148.41316 2980.958  ]], shape=(2, 2), dtype=float32)


In [75]:
tensorr

<tf.Variable 'Variable:0' shape=(2, 2, 8) dtype=int64, numpy=
array([[[0, 8, 5, 1, 2, 8, 4, 8],
        [1, 7, 9, 9, 3, 1, 7, 3]],

       [[2, 2, 3, 1, 6, 8, 0, 4],
        [5, 8, 0, 8, 0, 4, 5, 4]]], dtype=int64)>

In [76]:
tensorr*tensorr

<tf.Tensor: shape=(2, 2, 8), dtype=int64, numpy=
array([[[ 0, 64, 25,  1,  4, 64, 16, 64],
        [ 1, 49, 81, 81,  9,  1, 49,  9]],

       [[ 4,  4,  9,  1, 36, 64,  0, 16],
        [25, 64,  0, 64,  0, 16, 25, 16]]], dtype=int64)>

In [77]:
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[7., 9.],
       [5., 8.]], dtype=float32)>

In [78]:
c*c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[49., 81.],
       [25., 64.]], dtype=float32)>

In [79]:
# Broadcasting operation (element wise operation)
tensor = c * 5
tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[35., 45.],
       [25., 40.]], dtype=float32)>

In [80]:
# Matrix multiplication

In [81]:
# matrix mult'n of the square matrices

mat_a = tf.constant([[1,2],[3,4]])
mat_b = tf.constant([[1,2],[1,1]])
tf.matmul(mat_a, mat_b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 7, 10]])>

In [82]:
# matrix mult'n of the unordered matrices.

mat_a = tf.constant([[6,7,6]])
mat_b = tf.constant([[3,4,3]])
tf.matmul(mat_a, mat_b)

# the following opr'n gives erroe as we cant multiply mat of order 1x3 with 1x3.
# So we change to 1x3 and 3x1,  and we get a 1x1 output.
# Its called transpose of the matrix. see below cell.

InvalidArgumentError: Matrix size-incompatible: In[0]: [1,3], In[1]: [1,3] [Op:MatMul]

In [83]:
tf.matmul(mat_a, tf.transpose(mat_b))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[64]])>

In [84]:
# Type casting of tensor

tensorr

<tf.Variable 'Variable:0' shape=(2, 2, 8) dtype=int64, numpy=
array([[[0, 8, 5, 1, 2, 8, 4, 8],
        [1, 7, 9, 9, 3, 1, 7, 3]],

       [[2, 2, 3, 1, 6, 8, 0, 4],
        [5, 8, 0, 8, 0, 4, 5, 4]]], dtype=int64)>

In [85]:
i = tf.cast(tensorr, dtype=tf.float64,)
i

<tf.Tensor: shape=(2, 2, 8), dtype=float64, numpy=
array([[[0., 8., 5., 1., 2., 8., 4., 8.],
        [1., 7., 9., 9., 3., 1., 7., 3.]],

       [[2., 2., 3., 1., 6., 8., 0., 4.],
        [5., 8., 0., 8., 0., 4., 5., 4.]]])>

In [86]:
#Similarly
i = tf.dtypes.cast(tensorr, tf.int64)
i

<tf.Variable 'Variable:0' shape=(2, 2, 8) dtype=int64, numpy=
array([[[0, 8, 5, 1, 2, 8, 4, 8],
        [1, 7, 9, 9, 3, 1, 7, 3]],

       [[2, 2, 3, 1, 6, 8, 0, 4],
        [5, 8, 0, 8, 0, 4, 5, 4]]], dtype=int64)>

In [87]:
# Casting with truncation

j = tf.cast(tf.constant(4.8), dtype=tf.int64)
j

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [88]:
#ragged tensors: tensor having one or more ragged dimension.
# Ragged dimension : dimensions having slices having various length.
# declaration is shown below

In [89]:
ragged_tensor = tf.ragged.constant([[9,7,4,3,5,6,8,9],[],[11,12,13,15,19,20], [5],[-1,-5,-6]])
ragged_tensor

<tf.RaggedTensor [[9, 7, 4, 3, 5, 6, 8, 9], [], [11, 12, 13, 15, 19, 20], [5], [-1, -5, -6]]>

In [90]:
print(ragged_tensor[0,1])

tf.Tensor(7, shape=(), dtype=int32)


In [91]:
print(ragged_tensor[0,:])

tf.Tensor([9 7 4 3 5 6 8 9], shape=(8,), dtype=int32)


In [92]:
print(ragged_tensor[0,4:6])

tf.Tensor([5 6], shape=(2,), dtype=int32)


In [93]:
print(ragged_tensor[1,:])
print(ragged_tensor[2,:])
print(ragged_tensor[3,:])
print(ragged_tensor[4,:])

tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([11 12 13 15 19 20], shape=(6,), dtype=int32)
tf.Tensor([5], shape=(1,), dtype=int32)
tf.Tensor([-1 -5 -6], shape=(3,), dtype=int32)


In [94]:
# squared difference of the matrices.
# what it does is the find the difference and then square the result.

var_01 = tf.Variable([4,5,6,1,2])
var_02  = tf.Variable([8])
var_res = tf.math.squared_difference(var_01, var_02)
var_res

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([16,  9,  4, 49, 36])>

In [95]:
var_01 = tf.Variable([4,5,6,1,2])
var_02  = tf.Variable([4,0,0,0,0])
var_res = tf.math.squared_difference(var_01, var_02)
var_res

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 0, 25, 36,  1,  4])>

In [96]:
# Calculating the mean

numbers = tf.constant([[8,9],[1,2]], dtype=tf.float32)   # declaring a tensor
numbers

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[8., 9.],
       [1., 2.]], dtype=float32)>

In [97]:
tf.reduce_mean(input_tensor=numbers)           # finding mean throughout the data

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [98]:
tf.reduce_mean(input_tensor=numbers, axis=0)   #mean along row ,as axis = 0 =>imples row-wise

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.5, 5.5], dtype=float32)>

In [99]:
tf.reduce_mean(input_tensor=numbers, axis=1)  #mean along col ,as axis = 0 =>imples column-wise

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([8.5, 1.5], dtype=float32)>

In [100]:
# in simple we can write
tf.reduce_mean(numbers,0)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.5, 5.5], dtype=float32)>

In [101]:
# with keepdims = True , keeps the original dimension
 
print(tf.reduce_mean(input_tensor=numbers, axis=1))
print(tf.reduce_mean(input_tensor=numbers, axis=1, keepdims=True))

tf.Tensor([8.5 1.5], shape=(2,), dtype=float32)
tf.Tensor(
[[8.5]
 [1.5]], shape=(2, 1), dtype=float32)


In [105]:
# Saving and restoring using the checkpoint.

variable1 = tf.Variable([[5,6,9,3],[14,15,16,18]])
checkpoint = tf.train.Checkpoint(var = variable1)
savepath = checkpoint.save('./vars')
variable1.assign([[0,0,0,0],[0,0,0,0]])
variable1
checkpoint.restore(savepath)
print(variable1)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 5,  6,  9,  3],
       [14, 15, 16, 18]])>


In [103]:
# https://www.tensorflow.org/api_docs/python/tf 

# the important link for tensorflow documentation. visit the link for more information.

# The documentation also includes the keras information as well. 
# We can get indepth intuition of keras and its practical usage with theory by comparing both.
# We can also get the info of various optimizers, activators, loss fun'n, wt. initializers.